--DROP TABLE dbo.Roles
--GO

CREATE TABLE dbo.Roles(
       Id INT NOT NULL PRIMARY KEY,
	   AzureRoleId NVARCHAR(128),
       Name NVARCHAR(50)
       )
GO

DECLARE @v sql_variant 
SET @v = N'Table containing role category'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Roles'
GO

DECLARE @v sql_variant 
SET @v = N'Role Id'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Roles', N'COLUMN', N'Id'
GO

DECLARE @v sql_variant 
SET @v = N'GUID generated by developer and for Azure API use'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Roles', N'COLUMN', N'AzureRoleId'
GO

DECLARE @v sql_variant 
SET @v = N'Role Name'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Roles', N'COLUMN', N'Name'
GO

--DROP TABLE dbo.Users
--GO

CREATE TABLE dbo.Users(
       Id NVARCHAR(128) NOT NULL PRIMARY KEY,
       AzureAdId NVARCHAR(256),
       Email NVARCHAR(256),
       FirstName NVARCHAR(128),
       LastName NVARCHAR(128),
       DisplayName NVARCHAR(128),
       CreateTimeUtc DATETIME,
       IsRetired BIT
       )
GO

DECLARE @v sql_variant 
SET @v = N'Table containing all the CONNECT Users'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Users'
GO

DECLARE @v sql_variant 
SET @v = N'User ID'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Users', N'COLUMN', N'Id'
GO

DECLARE @v sql_variant 
SET @v = N'Azure created GUID, automatically created when add a user in CONNECT portal'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Users', N'COLUMN', N'AzureAdId'
GO

DECLARE @v sql_variant 
SET @v = N'Email of User'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Users', N'COLUMN', N'Email'
GO

DECLARE @v sql_variant 
SET @v = N'First name of User'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Users', N'COLUMN', N'FirstName'
GO

DECLARE @v sql_variant 
SET @v = N'Last name of User'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Users', N'COLUMN', N'LastName'
GO

DECLARE @v sql_variant 
SET @v = N'Create Time of a user'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Users', N'COLUMN', N'CreateTimeUtc'
GO

DECLARE @v sql_variant 
SET @v = N'1 if a user is deleted, 0 as active'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'Users', N'COLUMN', N'IsRetired'
GO

--DROP TABLE dbo.UserRoles
--GO

CREATE TABLE dbo.UserRoles(
       UserId NVARCHAR(128) FOREIGN KEY REFERENCES dbo.Users(Id),
       RoleId INT FOREIGN KEY REFERENCES dbo.Roles(Id),
	   AzureRltnId NVARCHAR(128),
	   CONSTRAINT FK_UserRoles_Users FOREIGN KEY (UserId)
			REFERENCES dbo.Users (Id) 
			ON DELETE CASCADE
			ON UPDATE CASCADE,
	   CONSTRAINT FK_UserRoles_Roles FOREIGN KEY (RoleId)
			REFERENCES dbo.Roles (Id) 
			ON DELETE CASCADE
			ON UPDATE CASCADE
      )
GO

DECLARE @v sql_variant 
SET @v = N'User ID, Foreign key on Users table'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'UserRoles', N'COLUMN', N'UserId'
GO

DECLARE @v sql_variant 
SET @v = N'Role ID, Foreign key on Roles table'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'UserRoles', N'COLUMN', N'RoleId'
GO

DECLARE @v sql_variant 
SET @v = N'ID generated by Azure when a role is assigned to a user; Will be used to delete the relationship of User&Role'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'UserRoles', N'COLUMN', N'AzureRltnId'
GO

--DROP TABLE dbo.AuditLogs
--GO

CREATE TABLE dbo.AuditLogs(
       Id BIGINT IDENTITY(1,1) NOT NULL,
       UserAzureAdId NVARCHAR(256) NOT NULL,
       IpAddress NVARCHAR(128) NULL,
       CategoryId INT NOT NULL,
       OperationId INT NOT NULL,
       OperationResultId INT NOT NULL,
       UtcTimestamp DATETIME NOT NULL,
       RecordData NVARCHAR(max) NULL,
       CONSTRAINT PK_AuditLogs PRIMARY KEY CLUSTERED (Id ASC) 
       WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
       ) 
ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

DECLARE @v sql_variant 
SET @v = N'Table containing all the audit logs, like login, logoff, add user, delete user, update user...'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'AuditLogs'
GO

DECLARE @v sql_variant 
SET @v = N'Log Event ID'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'AuditLogs', N'COLUMN', N'Id'
GO

DECLARE @v sql_variant 
SET @v = N'Azure created GUID, value same with dbo.User.AzureAdId'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'AuditLogs', N'COLUMN', N'UserAzureAdId'
GO

DECLARE @v sql_variant 
SET @v = N'IP Address of user login device '
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'AuditLogs', N'COLUMN', N'IpAddress'
GO

DECLARE @v sql_variant 
SET @v = N'Audit Operation ID: Login=1, LogoffManually = 2, LogoffAutomatically = 3, AddUser = 4,EditUser = 5, RetireUser = 6'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'AuditLogs', N'COLUMN', N'OperationId'
GO

DECLARE @v sql_variant 
SET @v = N'Audit Log Category ID: Unknown=0,UserManagement=1'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'AuditLogs', N'COLUMN', N'CategoryId'
GO

DECLARE @v sql_variant 
SET @v = N'Audit Operation Result ID: Unknown=0,SUCCESSFUL=1,FAILED=2'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'AuditLogs', N'COLUMN', N'OperationResultId'
GO

DECLARE @v sql_variant 
SET @v = N'Timestamp of the operation'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'AuditLogs', N'COLUMN', N'UtcTimestamp'
GO

DECLARE @v sql_variant 
SET @v = N'Detail information of the operation, stored in JSON format'
EXECUTE sp_addextendedproperty N'MS_Description', @v, N'SCHEMA', N'dbo', N'TABLE', N'AuditLogs', N'COLUMN', N'RecordData'
GO