//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfDemo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EfDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*************************************************************
        ///Description: create schema level security for Connect project
        ///History:
        ///    * Add from v1.0
        ///*************************************************************/
        ///
        ///--create user login
        ///IF  EXISTS (SELECT name FROM master.sys.server_principals WHERE name = &apos;CTS_Prod&apos;)
        ///DROP LOGIN CTS_Prod;  
        ///GO
        ///
        ///-- create LOGIN under &quot;master&quot; DB
        ///CREATE LOGIN CTS_Prod WITH PASSWORD = N&apos;connectp@55w0rd&apos;
        ///GO
        ///
        ///
        ///--create user in BeckmanConnect database &quot;CTS_DEV&quot;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string create_schema_level_security_v1_0 {
            get {
                return ResourceManager.GetString("create_schema_level_security_v1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --DROP TABLE CTS.Roles
        ///--GO
        ///
        ///CREATE TABLE CTS.Roles(
        ///       Id INT NOT NULL PRIMARY KEY,
        ///	   AzureRoleId NVARCHAR(128),
        ///       Name NVARCHAR(50)
        ///       )
        ///GO
        ///
        ///DECLARE @v sql_variant 
        ///SET @v = N&apos;Table containing role category&apos;
        ///EXECUTE sp_addextendedproperty N&apos;MS_Description&apos;, @v, N&apos;SCHEMA&apos;, N&apos;CTS&apos;, N&apos;TABLE&apos;, N&apos;Roles&apos;
        ///GO
        ///
        ///DECLARE @v sql_variant 
        ///SET @v = N&apos;Role Id&apos;
        ///EXECUTE sp_addextendedproperty N&apos;MS_Description&apos;, @v, N&apos;SCHEMA&apos;, N&apos;CTS&apos;, N&apos;TABLE&apos;, N&apos;Roles&apos;, N&apos;COLUMN&apos;, N&apos;Id&apos;
        ///GO
        ///
        ///DECLARE @v sq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string create_tables_v1_0 {
            get {
                return ResourceManager.GetString("create_tables_v1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- init Roles 
        ///INSERT INTO CTS.Roles(Id,AzureRoleId,Name) VALUES(1,&apos;76f938d6-b970-497d-a500-72277bc75011&apos;,&apos;Administrator&apos;),(2,&apos;5c6a8000-3497-4bd3-983a-ad4f5d8ceefe&apos;,&apos;User&apos;)
        ///GO
        ///
        ///-- init Users
        ///
        ///-- init UserRoles
        ///.
        /// </summary>
        internal static string InitialData_v1_0 {
            get {
                return ResourceManager.GetString("InitialData_v1_0", resourceCulture);
            }
        }
    }
}
